/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.AsiloController;
import controller.AsiloController;
import java.awt.Color;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import javax.swing.plaf.ColorUIResource;
import model.Asilo;

/**
 *
 * @author saraa
 */
public class AsiloUI extends javax.swing.JFrame {

    AsiloController controll = new AsiloController();
    Asilo asilo = controll.getAsilo();
    Color bgColor = new Color(35,31,31);
    Color txtColor = new Color(86,86,86);
    Color fontColor = new Color(196,187,187);

    public AsiloUI() {
        try {
            UIManager.setLookAndFeel("FlatLaf");
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
        }

        initComponents();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        if (asilo != null) {
            this.txtNome.setText(asilo.getNome());
            this.txtEmail.setText(asilo.getEmail());
            this.txtTel.setText(asilo.getTelefone());
            this.txtPix.setText(asilo.getChavePix());
            this.txtEnd.setText(asilo.getEndereco());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        head = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPix = new javax.swing.JTextField();
        txtTel = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtEnd = new javax.swing.JTextField();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane4.setViewportView(jTextArea3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(35, 31, 31));
        jPanel1.setForeground(new java.awt.Color(196, 187, 187));
        jPanel1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        head.setBackground(new java.awt.Color(196, 187, 187));
        head.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        head.setForeground(new java.awt.Color(200, 200, 200));
        head.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        head.setText("O Asilo");

        jLabel2.setBackground(new java.awt.Color(196, 187, 187));
        jLabel2.setForeground(new java.awt.Color(200, 200, 200));
        jLabel2.setText("Nome");

        jLabel3.setBackground(new java.awt.Color(196, 187, 187));
        jLabel3.setForeground(new java.awt.Color(200, 200, 200));
        jLabel3.setText("E-mail");

        jLabel4.setBackground(new java.awt.Color(196, 187, 187));
        jLabel4.setForeground(new java.awt.Color(200, 200, 200));
        jLabel4.setText("Tel");

        btn.setBackground(new java.awt.Color(102, 102, 102));
        btn.setForeground(new java.awt.Color(220, 220, 200));
        btn.setText("Editar");
        btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        btn.setFocusPainted(false);
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(196, 187, 187));
        jLabel1.setForeground(new java.awt.Color(200, 200, 200));
        jLabel1.setText("Pix");

        jLabel5.setBackground(new java.awt.Color(196, 187, 187));
        jLabel5.setForeground(new java.awt.Color(200, 200, 200));
        jLabel5.setText("Enderço");

        txtPix.setBackground(new java.awt.Color(35, 31, 31));
        txtPix.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtPix.setForeground(new java.awt.Color(200, 200, 200));
        txtPix.setBorder(null);
        txtPix.setCaretColor(new java.awt.Color(196, 187, 187));
        txtPix.setDisabledTextColor(new java.awt.Color(196, 187, 187));
        txtPix.setEnabled(false);
        txtPix.setMinimumSize(new java.awt.Dimension(64, 26));
        txtPix.setPreferredSize(new java.awt.Dimension(64, 26));
        txtPix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPixActionPerformed(evt);
            }
        });

        txtTel.setBackground(new java.awt.Color(35, 31, 31));
        txtTel.setForeground(new java.awt.Color(200, 200, 200));
        txtTel.setBorder(null);
        txtTel.setCaretColor(new java.awt.Color(196, 187, 187));
        txtTel.setDisabledTextColor(new java.awt.Color(196, 187, 187));
        txtTel.setEnabled(false);
        txtTel.setPreferredSize(new java.awt.Dimension(64, 26));

        txtEmail.setBackground(new java.awt.Color(35, 31, 31));
        txtEmail.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(200, 200, 200));
        txtEmail.setBorder(null);
        txtEmail.setCaretColor(new java.awt.Color(196, 187, 187));
        txtEmail.setDisabledTextColor(new java.awt.Color(196, 187, 187));
        txtEmail.setEnabled(false);
        txtEmail.setPreferredSize(new java.awt.Dimension(64, 26));

        txtNome.setBackground(new java.awt.Color(35, 31, 31));
        txtNome.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtNome.setForeground(new java.awt.Color(200, 200, 200));
        txtNome.setBorder(null);
        txtNome.setCaretColor(new java.awt.Color(196, 187, 187));
        txtNome.setDisabledTextColor(new java.awt.Color(196, 187, 187));
        txtNome.setEnabled(false);
        txtNome.setPreferredSize(new java.awt.Dimension(64, 26));
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        txtEnd.setBackground(new java.awt.Color(35, 31, 31));
        txtEnd.setForeground(new java.awt.Color(200, 200, 200));
        txtEnd.setBorder(null);
        txtEnd.setCaretColor(new java.awt.Color(196, 187, 187));
        txtEnd.setDisabledTextColor(new java.awt.Color(196, 187, 187));
        txtEnd.setEnabled(false);
        txtEnd.setMinimumSize(new java.awt.Dimension(64, 26));
        txtEnd.setPreferredSize(new java.awt.Dimension(64, 26));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPix, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEnd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(head)
                    .addComponent(btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(head)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(btn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed

        if (this.btn.getText() == "Editar") {
            this.txtNome.setEnabled(true);
            this.txtEmail.setEnabled(true);
            this.txtTel.setEnabled(true);
            this.txtEnd.setEnabled(true);
            this.txtPix.setEnabled(true);
            this.btn.setText("Salvar");
            this.txtNome.setBackground(txtColor);
            this.txtEmail.setBackground(txtColor);
            this.txtTel.setBackground(txtColor);
            this.txtEnd.setBackground(txtColor);
            this.txtPix.setBackground(txtColor);
        } else {
            String nome = this.txtNome.getText();
            String email = this.txtEmail.getText();
            String tel = this.txtTel.getText();
            String end = this.txtEnd.getText();
            String pix = this.txtPix.getText();
            if (asilo != null) {
                controll.atualizarAsilo(nome, end, tel, email, pix);
            } else {
                controll.cadastrarAsilo(nome, end, tel, email, pix);
            }
            this.txtNome.setEnabled(false);
            this.txtEmail.setEnabled(false);
            this.txtTel.setEnabled(false);
            this.txtEnd.setEnabled(false);
            this.txtPix.setEnabled(false);
            this.btn.setText("Editar");
            this.txtNome.setBackground(bgColor);
            this.txtEmail.setBackground(bgColor);
            this.txtTel.setBackground(bgColor);
            this.txtEnd.setBackground(bgColor);
            this.txtPix.setBackground(bgColor);
        }
    }//GEN-LAST:event_btnActionPerformed

    private void txtPixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPixActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AsiloUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn;
    private javax.swing.JLabel head;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEnd;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPix;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables
}
